import os
import numpy as np
from PIL import Image

# ============================================================
# SAFE ANDROID TENSORFLOW LITE IMPORT BYPASS (UPDATED)
# ============================================================
try:
    try:
        from tflite_runtime.interpreter import Interpreter
    except ImportError:
        from tensorflow.lite.python.interpreter import Interpreter
    TFLITE_AVAILABLE = True
except Exception as e:
    print(f"⚠️ TFLite unavailable: {e}")
    TFLITE_AVAILABLE = False

# ============================================================
# ROBUST PATH CONTEXT RESOLUTION & LOGGING
# ============================================================
CWD = os.getcwd()
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Define permutations where the model might sit during desktop run vs android build
# Prioritizes the retrained V2 model, with automatic fallback to V1 baseline
POSSIBLE_PATHS = [
    os.path.join(BASE_DIR, "models", "tomato_disease_model_v2.tflite"),
    os.path.join(BASE_DIR, "..", "models", "tomato_disease_model_v2.tflite"),
    os.path.join(BASE_DIR, "..", "disease", "models", "tomato_disease_model_v2.tflite"),
    os.path.join(CWD, "disease", "models", "tomato_disease_model_v2.tflite"),
    os.path.join(CWD, "models", "tomato_disease_model_v2.tflite"),
    os.path.join(BASE_DIR, "models", "tomato_disease_model.tflite"),
    os.path.join(BASE_DIR, "..", "models", "tomato_disease_model.tflite"),
    os.path.join(BASE_DIR, "..", "disease", "models", "tomato_disease_model.tflite"),
    os.path.join(CWD, "disease", "models", "tomato_disease_model.tflite"),
    os.path.join(CWD, "models", "tomato_disease_model.tflite")
]

# Debug logs to verify exact tracking inside Android logcat / command line
print("===== MODEL SEARCH =====")
for p in POSSIBLE_PATHS:
    print(os.path.abspath(p), "->", os.path.exists(p))

MODEL_PATH = None
for p in POSSIBLE_PATHS:
    normalized_p = os.path.normpath(p)
    if os.path.exists(normalized_p):
        MODEL_PATH = normalized_p
        break

if not MODEL_PATH:
    # Strict dynamic absolute fallback assignment
    MODEL_PATH = os.path.normpath(os.path.join(BASE_DIR, "models", "tomato_disease_model_v2.tflite"))

print("Selected:", os.path.abspath(MODEL_PATH))

# 💡 Empirically calibrated threshold derived from validation PR-curve (maximizing F1: 0.9504)
CONFIDENCE_THRESHOLD = 0.65
ENTROPY_THRESHOLD = 0.55  # Flags ambiguous or out-of-distribution inputs

# Ensure keys map exactly to the alphabetical folders generated by flow_from_directory:
CLASS_MAPPING = {
    0: "Early Blight",
    1: "Healthy",
    2: "Late Blight",
    3: "Leaf Miner Infestation"
}

DISEASE_INFO = {
    "Healthy": {
        "en": {
            "title": "Healthy Crop",
            "symptoms": [
                "Leaves are uniformly green with no visible spots or discoloration.",
                "No holes, lesions, or signs of insect damage.",
                "Plant shows healthy and vigorous growth."
            ],
            "treatment": "No treatment is required. Continue regular crop care and monitoring.",
            "prevention": [
                "Water plants regularly without overwatering.",
                "Apply balanced fertilizers as recommended.",
                "Inspect plants frequently for early signs of pests or diseases.",
                "Maintain proper spacing for good air circulation."
            ]
        },
        "ne": {
            "title": "स्वस्थ बाली (Healthy Crop)",
            "symptoms": [
                "पातहरू कतै पनि दाग वा रङ परिवर्तन नभई समान रूपमा हरिया छन्।",
                "पातमा कुनै प्वाल, घाउ वा कीराको क्षतिका लक्षणहरू छैनन्।",
                "बोटले स्वस्थ र राम्रो वृद्धि विकास देखाउँछ।"
            ],
            "treatment": "कुनै उपचार आवश्यक छैन। नियमित बाली हेरचाह र अनुगमन जारी राख्नुहोस्।",
            "prevention": [
                "बोटबिरुवामा बढी पानी नजम्ने गरी नियमित सिँचाइ गर्नुहोस्।",
                "सिफारिस गरिए अनुसार सन्तुलित मल प्रयोग गर्नुहोस्।",
                "कीरा वा रोगहरूको प्रारम्भिक लक्षणहरूको लागि बोटबिरुवाहरू बारम्बार निरीक्षण गर्नुहोस्।",
                "राम्रो हावा आवतजावतको लागि बिरुवाहरू बीच उचित दूरी कायम राख्नुहोस्।"
            ]
        }
    },
    "Early Blight": {
        "en": {
            "title": "Tomato - Early Blight",
            "pathogen": "Fungus",
            "scientific_name": "Alternaria solani",
            "symptoms": [
                "Small brown or black spots appear on older leaves.",
                "Spots develop concentric ring patterns (target-like appearance).",
                "Leaves gradually turn yellow and dry out.",
                "Infected leaves may fall prematurely."
            ],
            "treatment": "Remove infected leaves and apply a recommended fungicide. Spray Mancozeb 75% WP @ 2–2.5 g/L water or Chlorothalonil 75% WP @ 2 g/L water. Avoid overhead irrigation and dispose of infected plant debris.",
            "prevention": [
                "Practice crop rotation.",
                "Maintain proper spacing between plants.",
                "Avoid watering the leaves directly.",
                "Remove infected plant debris after harvest.",
                "Use disease-free seeds or seedlings."
            ]
        },
        "ne": {
            "title": "टमाटर - प्रारम्भिक ब्लाइट (Early Blight)",
            "pathogen": "ढुसी (Fungus)",
            "scientific_name": "Alternaria solani",
            "symptoms": [
                "पुराना पातहरूमा साना खैरो वा कालो दागहरू देखा पर्छन्।",
                "दागहरूमा चक्राकार घेराहरू विकसित हुन्छन् (निशाना जस्तो देखिने)।",
                "पातहरू बिस्तारै पहेंलो हुँदै जान्छन् र सुक्छन्।",
                "संक्रमित पातहरू समय भन्दा पहिले नै खस्न सक्छन्।"
            ],
            "treatment": "संक्रमित पातहरू हटाउनुहोस्। Mancozeb 75% WP प्रति लिटर पानीमा २–२.५ ग्राम वा Chlorothalonil 75% WP प्रति लिटर पानीमा २ ग्रामको दरले छर्कनुहोस्। बोटको माथिबाट सिँचाइ नगर्नुहोस् र संक्रमित बिरुवाका अवशेषहरू नष्ट गर्नुहोस्।",
            "prevention": [
                "बाली चक्र (Crop Rotation) अपनाउनुहोस्।",
                "बिरुवाहरू बीच उचित दूरी कायम राख्नुहोस्।",
                "पातहरूमा सिधै पानी हाल्नबाट जोगिनुहोस्।",
                "बाली भित्र्याएपछि संक्रमित बिरुवाका अवशेषहरू खेतबाट हटाउनुहोस्।",
                "रोगमुक्त बीउ वा बेर्नाहरू मात्र प्रयोग गर्नुहोस्।"
            ]
        }
    },
    "Late Blight": {
        "en": {
            "title": "Tomato - Late Blight",
            "pathogen": "Fungus (Water Mold)",
            "scientific_name": "Phytophthora infestans",
            "symptoms": [
                "Large dark brown or black water-soaked lesions appear on leaves.",
                "White fungal growth may appear on the underside of infected leaves during humid conditions.",
                "Leaves wilt rapidly and become brown.",
                "The disease spreads quickly during cool and wet weather."
            ],
            "treatment": "Remove infected plants immediately. Spray Metalaxyl + Mancozeb @ 2 g/L water and repeat every 7–10 days during favorable weather. Avoid excessive moisture around the crop.",
            "prevention": [
                "Improve field drainage.",
                "Provide adequate spacing for airflow.",
                "Avoid prolonged leaf wetness.",
                "Inspect crops regularly during rainy seasons.",
                "Use resistant tomato varieties whenever possible."
            ]
        },
        "ne": {
            "title": "टमाटर - पछौटे ब्लाइट (Late Blight)",
            "pathogen": "ढुसी (Water Mold)",
            "scientific_name": "Phytophthora infestans",
            "symptoms": [
                "पातहरूमा ठूला, गाढा खैरो वा कालो पानीले भिजेका जस्ता दागहरू देखा पर्छन्।",
                "अत्यधिक ओसिलो मौसममा संक्रमित पातहरूको तल्लो भागमा सेतो ढुसी देखा पर्न सक्छ।",
                "पातहरू द्रुत रूपमा ओइलाउँछन् र खैरो हुन्छन्।",
                "चिसो र ओसिलो मौसममा यो रोग चाँडै फैलिन्छ।"
            ],
            "treatment": "संक्रमित बिरुवाहरू तुरुन्तै हटाउनुहोस्। Metalaxyl + Mancozeb प्रति लिटर पानीमा २ ग्रामको दरले छर्कनुहोस् र अनुकूल मौसममा प्रत्येक ७–१० दिनमा दोहोर्याउनुहोस्। बाली वरपर अत्यधिक चिसो वा ओस हुन नदिनुहोस्।",
            "prevention": [
                "खेतको ड्रेनेज (पानी निकास) व्यवस्था सुधार गर्नुहोस्।",
                "हावा आवतजावतका लागि बिरुवाहरू बीच पर्याप्त दूरी राख्नुहोस्।",
                "पातहरू लामो समयसम्म भिजिरहने अवस्था हुन नदिनुहोस्।",
                "वर्षाको मौसममा नियमित रूपमा बाली निरीक्षण गर्नुहोस्।",
                "सकेसम्म रोग प्रतिरोधात्मक टमाटरका जातहरू प्रयोग गर्नुहोस्।"
            ]
        }
    },
    "Leaf Miner Infestation": {
        "en": {
            "title": "Tomato - Leaf Miner Infestation",
            "pathogen": "Insect Pest",
            "scientific_name": "Liriomyza trifolii",
            "symptoms": [
                "White or light-colored winding tunnels appear inside the leaves.",
                "Leaves develop irregular mined patterns.",
                "Heavy infestation reduces photosynthesis.",
                "Leaves may dry and fall prematurely."
            ],
            "treatment": "Remove heavily infested leaves. Spray Spinosad 45 SC @ 0.3 ml/L water. Rotate insecticides with different modes of action to reduce resistance.",
            "prevention": [
                "Monitor crops regularly for early infestation.",
                "Remove affected leaves promptly.",
                "Keep the field free from weeds that may host leaf miners.",
                "Encourage natural predators such as parasitic wasps.",
                "Practice good field sanitation."
            ]
        },
        "ne": {
            "title": "लीफ माइनरको प्रकोप (Leaf Miner Infestation)",
            "pathogen": "कीरा (Insect Pest)",
            "scientific_name": "Liriomyza trifolii",
            "symptoms": [
                "पातहरू भित्र सेतो वा हल्का रङको घुमाउरो सुरुङ जस्ता धर्काहरू देखा पर्छन्।",
                "पातहरूमा अनियमित आकारका बुट्टाहरू जस्तै प्याटर्न बन्छन्।",
                "अत्यधिक प्रकोपले पातको प्रकाश संश्लेषण प्रक्रिया घटाउँछ।",
                "पातहरू सुक्न सक्छन् र समय भन्दा पहिले नै खस्न सक्छन्।"
            ],
            "treatment": "अत्यधिक संक्रमित पातहरू हटाउनुहोस्। Spinosad 45 SC प्रति लिटर पानीमा ०.३ मिलिलिटरको दरले छर्कनुहोस्। प्रतिरोध क्षमता कम गर्न फरक-फरक प्रकारका कीटनाशकहरू पालैपालो प्रयोग गर्नुहोस्।",
            "prevention": [
                "प्रारम्भिक प्रकोप पहिचान गर्न नियमित रूपमा बालीको अनुगमन गर्नुहोस्।",
                "असर परेका पातहरू तुरुन्तै टिपेर नष्ट गर्नुहोस्।",
                "लीफ माइनरलाई आश्रय दिने झारपातहरू खेतमा बढ्न नदिनुहोस्।",
                "परजीवी बारुला (Parasitic Wasps) जस्ता प्राकृतिक शत्रु जीवहरूलाई प्रोत्साहन गर्नुहोस्।",
                "खेतबारीको सरसफाइमा विशेष ध्यान दिनुहोस्।"
            ]
        }
    }
}

FALLBACK_INFO = {
    "en": {
        "title": "Unable to Identify Leaf",
        "text": "The uploaded photo does not closely resemble a plant leaf or the image is unclear. Please capture a clear photo focusing directly on the leaf structure."
    },
    "ne": {
        "title": "पात पहिचान हुन सकेन",
        "text": "अपलोड गरिएको तस्बिर बिरुवाको पातसँग मेल खाएन वा स्पष्ट भएन। कृपया पात स्पष्ट देखिने गरी नजिकबाट अर्को तस्बिर खिच्नुहोस् वा अपलोड गर्नुहोस्।"
    }
}

# Persistent references to speed up sequential application responses
_interpreter = None
_input_details = None
_output_details = None

def to_nepali_digits(number):
    nep_digits = {"0": "०", "1": "१", "2": "२", "3": "३", "4": "४", "5": "५", "6": "६", "7": "७", "8": "८", "9": "९", ".": "."}
    return "".join(nep_digits.get(ch, ch) for ch in str(number))

def get_model():
    global _interpreter, _input_details, _output_details

    if not TFLITE_AVAILABLE:
        return None

    if _interpreter is None:
        if os.path.exists(MODEL_PATH):
            try:
                _interpreter = Interpreter(model_path=MODEL_PATH)
                _interpreter.allocate_tensors()

                _input_details = _interpreter.get_input_details()
                _output_details = _interpreter.get_output_details()

                print("✅ TFLite model loaded")
            except Exception as e:
                print(f"⚠️ TFLite loading error: {e}")
                _interpreter = None
        else:
            print(f"⚠️ Model missing: {os.path.abspath(MODEL_PATH)}")

    return _interpreter

def predict_disease(image_path, language="ne"):
    # Fallback gracefully to demo/defense data if TFLite is missing or setup fails
    if not TFLITE_AVAILABLE:
        demo_title = "Early Blight (Demo Mode)" if language == "en" else "प्रारम्भिक ब्लाइट (डेमो मोड)"
        demo_confidence = "90.0%" if language == "en" else "९०.०%"
        demo_treatment = (
            "[b]Demo Mode Active[/b]\n"
            "TFLite is not installed on this system.\n\n"
            "[b]Recommended Care:[/b]\n"
            "• Remove early infected leaves to prevent field spread.\n"
            "• Avoid overhead watering to reduce wet surface periods.\n"
            "• Consult your local agricultural agent."
        ) if language == "en" else (
            "[b]डेमो मोड सक्रिय छ[/b]\n"
            "यस प्रणालीमा TFLite जडान गरिएको छैन।\n\n"
            "[b]सिफारिस गरिएको उपचार र हेरचाह:[/b]\n"
            "• संक्रमण फैलन नदिन प्रारम्भिक संक्रमित पातहरू हटाउनुहोस्।\n"
            "• पातहरू लामो समयसम्म भिज्न नदिन बोटको फेदमा मात्र पानी हाल्नुहोस्।\n"
            "• थप जानकारीको लागि कृषि प्राविधिकसँग परामर्श गर्नुहोस्।"
        )

        return {
            "title": demo_title,
            "confidence": demo_confidence,
            "treatment": demo_treatment
        }

    interpreter = get_model()
    if interpreter is None:
        return {
            "title": "Model Error" if language == "en" else "मोडेल त्रुटि",
            "confidence": "0.0%",
            "treatment": f"Model file not found. Checked path: {os.path.abspath(MODEL_PATH)}" if language == "en" else f"मोडेल फेला परेन। जाँच गरिएको मार्ग: {os.path.abspath(MODEL_PATH)}"
        }

    try:
        # Load and process image using PIL to bypass heavy Keras infrastructure dependencies
        img = Image.open(image_path).convert("RGB")
        img = img.resize((224, 224))
        # Official MobileNetV2 preprocessing: scale to [-1, 1]
        img_array = (np.array(img, dtype=np.float32) / 127.5) - 1.0
        img_array = np.expand_dims(img_array, axis=0)

        # Run inference
        interpreter.set_tensor(_input_details[0]["index"], img_array.astype(np.float32))
        interpreter.invoke()
        
        predictions = interpreter.get_tensor(_output_details[0]["index"])
        best_idx = int(np.argmax(predictions[0]))
        confidence = float(predictions[0][best_idx])

        # Normalized Shannon entropy calculation for ambiguity detection
        eps = 1e-12
        entropy = -np.sum(predictions[0] * np.log(predictions[0] + eps)) / np.log(len(CLASS_MAPPING))

        # Trigger fallback card if result is below calibrated threshold or has high ambiguity
        if confidence < CONFIDENCE_THRESHOLD or entropy > ENTROPY_THRESHOLD:
            fallback = FALLBACK_INFO[language]
            conf_label = f"Confidence: {round(confidence * 100, 1)}%" if language == "en" else f"विश्वसनीयता : {to_nepali_digits(round(confidence * 100, 1))}%"
            return {
                "title": fallback["title"],
                "confidence": conf_label,
                "treatment": fallback["text"]
            }

        class_name = CLASS_MAPPING.get(best_idx, "Healthy")
        info = DISEASE_INFO[class_name][language]

        # Structuring headings based on chosen localization configuration
        symptoms_heading = "Symptoms:" if language == "en" else "लक्षणहरू:"
        treatment_heading = "Treatment:" if language == "en" else "उपचार:"
        prevention_heading = "Prevention:" if language == "en" else "रोकथामका उपायहरू:"

        formatted_symptoms = "\n".join([f"• {s}" for s in info["symptoms"]])
        formatted_prevention = "\n".join([f"• {p}" for p in info["prevention"]])

        full_details = (
            f"[b]{symptoms_heading}[/b]\n{formatted_symptoms}\n\n"
            f"[b]{treatment_heading}[/b]\n• {info['treatment']}\n\n"
            f"[b]{prevention_heading}[/b]\n{formatted_prevention}"
        )

        if language == "ne":
            conf_label = f"विश्वसनीयता : {to_nepali_digits(round(confidence * 100, 1))}%"
        else:
            conf_label = f"Confidence: {round(confidence * 100, 1)}%"

        return {
            "title": info["title"],
            "confidence": conf_label,
            "treatment": full_details
        }

    except Exception as e:
        print(f"Prediction error: {e}")
        fallback = FALLBACK_INFO[language]
        return {
            "title": fallback["title"],
            "confidence": "",
            "treatment": fallback["text"]
        }